// <auto-generated />
using System;
using CsharpWebApiDotNetCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CsharpWebApiDotNetCore.Migrations
{
    [DbContext(typeof(AirDBContext))]
    [Migration("20230413191849_mkrea")]
    partial class mkrea
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CsharpWebApiDotNetCore.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test@test.nl",
                            FirstName = "Test",
                            LastName = "Test"
                        });
                });

            modelBuilder.Entity("CsharpWebApiDotNetCore.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsCover")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCover = true,
                            LocationId = 1,
                            Url = "https://th.bing.com/th/id/OIP.4XB8NF1awQyApnQDDmBmQwHaEo?pid=ImgDet&rs=1"
                        },
                        new
                        {
                            Id = 2,
                            IsCover = false,
                            LocationId = 1,
                            Url = "https://th.bing.com/th/id/R.7a5b8b8f2c06d86438fa0ca1d1a6e81e?rik=6mW1IbIQA718KQ&pid=ImgRaw&r=0"
                        },
                        new
                        {
                            Id = 3,
                            IsCover = true,
                            LocationId = 2,
                            Url = "https://th.bing.com/th/id/OIP.rt-pujAJJlfsYntGE4rRAgHaE7?pid=ImgDet&rs=1"
                        },
                        new
                        {
                            Id = 4,
                            IsCover = false,
                            LocationId = 2,
                            Url = "https://th.bing.com/th/id/R.1ac8616cc26c5ffa5d4a124e068c447d?rik=Q3ad8plACqWAMQ&riu=http%3a%2f%2flovelyfotos.l.o.pic.centerblog.net%2fo%2f98a8ed98.jpg&ehk=oMZ4%2bUZ%2b2P7UvBelRgLJi%2fXMGMrpqfqtm%2bTC58Gqtbg%3d&risl=&pid=ImgRaw&r=0"
                        },
                        new
                        {
                            Id = 5,
                            IsCover = true,
                            LocationId = 3,
                            Url = "https://miro.medium.com/v2/resize:fit:3840/1*xMuIOwjliGUPjkzukeWKfw.jpeg"
                        },
                        new
                        {
                            Id = 6,
                            IsCover = false,
                            LocationId = 3,
                            Url = "https://th.bing.com/th/id/OIP.L51qzGCLtslIZn42Q0BFhgHaE7?pid=ImgDet&rs=1"
                        },
                        new
                        {
                            Id = 7,
                            IsCover = true,
                            LocationId = 4,
                            Url = "https://pixy.org/src/21/219269.jpg"
                        },
                        new
                        {
                            Id = 8,
                            IsCover = false,
                            LocationId = 4,
                            Url = "https://th.bing.com/th/id/R.551cf68432c7dd0c1ddfebb77c484b16?rik=4BRITn7IBb7E5A&riu=http%3a%2f%2fthewowstyle.com%2fwp-content%2fuploads%2f2015%2f07%2f3d-only-natural-backgrounds-wallpapers.jpg&ehk=PKY8ZDTMjVdIJyFK3s1z1hshGDDLPv3Igu1kxcN3yH8%3d&risl=&pid=ImgRaw&r=0"
                        },
                        new
                        {
                            Id = 9,
                            IsCover = true,
                            LocationId = 5,
                            Url = "https://images.toucharger.com/img/graphiques/fonds-d-ecran/nature--paysages/coucher-de-soleil/polynesie.72440.jpg"
                        },
                        new
                        {
                            Id = 10,
                            IsCover = false,
                            LocationId = 5,
                            Url = "https://www.freepsdbazaar.com/wp-content/uploads/2020/06/sky-night/night-sky-049.jpg"
                        },
                        new
                        {
                            Id = 11,
                            IsCover = true,
                            LocationId = 6,
                            Url = "https://th.bing.com/th/id/R.35b7cf10203ae316c59e65b9f0c6d60d?rik=PEZxCxVcGh5lEw&riu=http%3a%2f%2fs1.picswalls.com%2fwallpapers%2f2017%2f12%2f11%2fnature-desktop-background_123026895_313.jpg&ehk=rvr98svQL12hNeYouWPK7AvyXVnHaRJWDvovllsJxRs%3d&risl=1&pid=ImgRaw&r=0"
                        },
                        new
                        {
                            Id = 12,
                            IsCover = false,
                            LocationId = 6,
                            Url = "https://images.toucharger.com/img/graphiques/fonds-d-ecran/nature-paysages/coucher-de-soleil/coucher-de-soleil.74120.jpg"
                        },
                        new
                        {
                            Id = 13,
                            IsCover = true,
                            LocationId = 7,
                            Url = "https://th.bing.com/th/id/R.0d045617037f9cef063d1a9dfe2646b7?rik=EswZh150nqhxsg&riu=http%3a%2f%2fwww.snut.fr%2fwp-content%2fuploads%2f2015%2f07%2fimage-de-fleur-6.jpg&ehk=M9uLBYMHQgtcByG2fGYQSKyylapb%2bfCApnNYShcBdfE%3d&risl=&pid=ImgRaw&r=0"
                        },
                        new
                        {
                            Id = 14,
                            IsCover = false,
                            LocationId = 7,
                            Url = "https://th.bing.com/th/id/R.3bcb9885029ffb81f58fb4a46c6d854f?rik=caTmTHH%2bNuWv1w&riu=http%3a%2f%2fgetwallpapers.com%2fwallpaper%2ffull%2f8%2fd%2f1%2f798741-download-free-awesome-nature-backgrounds-1920x1080-for-tablet.jpg&ehk=%2fu8xawhlqhlABfauhjBvJm3YUpEq5Vjqj2FfHAGm%2bj8%3d&risl=&pid=ImgRaw&r=0"
                        },
                        new
                        {
                            Id = 15,
                            IsCover = true,
                            LocationId = 8,
                            Url = "https://cdn.wallpapersafari.com/43/42/IwWBH3.jpg"
                        },
                        new
                        {
                            Id = 16,
                            IsCover = false,
                            LocationId = 8,
                            Url = "https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2017/11/autumn_fireball/17255671-1-eng-GB/Autumn_fireball.jpg"
                        },
                        new
                        {
                            Id = 17,
                            IsCover = true,
                            LocationId = 9,
                            Url = "https://goldwallpapers.com/uploads/posts/jpeg-wallpapers/jpeg_wallpapers_026.jpg"
                        },
                        new
                        {
                            Id = 18,
                            IsCover = false,
                            LocationId = 9,
                            Url = "https://images4.alphacoders.com/115/thumb-1920-115716.jpg"
                        },
                        new
                        {
                            Id = 19,
                            IsCover = true,
                            LocationId = 10,
                            Url = "https://th.bing.com/th/id/OIP.4XB8NF1awQyApnQDDmBmQwHaEo?pid=ImgDet&rs=1"
                        },
                        new
                        {
                            Id = 20,
                            IsCover = false,
                            LocationId = 10,
                            Url = "https://www.imagelighteditor.com/img/bg-after.jpg"
                        },
                        new
                        {
                            Id = 21,
                            IsCover = false,
                            Url = "https://www.pixelstalk.net/wp-content/uploads/2016/06/Free-Download-HD-Country-Image.jpg"
                        },
                        new
                        {
                            Id = 22,
                            IsCover = false,
                            Url = "https://i.ytimg.com/vi/xS-gJydZXuM/maxresdefault.jpg"
                        },
                        new
                        {
                            Id = 23,
                            IsCover = false,
                            Url = "https://www.wallpapertip.com/wmimgs/8-82164_soothing-background.jpg"
                        });
                });

            modelBuilder.Entity("CsharpWebApiDotNetCore.Models.Landlord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Landlord");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 1,
                            AvatarId = 21,
                            FirstName = "Jeffry",
                            LastName = "Bahmer"
                        },
                        new
                        {
                            Id = 2,
                            Age = 1,
                            AvatarId = 22,
                            FirstName = "Deffry",
                            LastName = "Dahmer"
                        },
                        new
                        {
                            Id = 3,
                            Age = 1,
                            AvatarId = 23,
                            FirstName = "Teffry",
                            LastName = "Tahmer"
                        });
                });

            modelBuilder.Entity("CsharpWebApiDotNetCore.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Features")
                        .HasColumnType("int");

                    b.Property<int?>("LandlordId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<float>("PricePerDay")
                        .HasColumnType("real");

                    b.Property<int>("Rooms")
                        .HasColumnType("int");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LandlordId");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description1",
                            Features = 1,
                            LandlordId = 1,
                            NumberOfGuests = 4,
                            PricePerDay = 20f,
                            Rooms = 2,
                            SubTitle = "SubTitle1",
                            Title = "House1",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description2",
                            Features = 2,
                            LandlordId = 1,
                            NumberOfGuests = 4,
                            PricePerDay = 30f,
                            Rooms = 2,
                            SubTitle = "SubTitle2",
                            Title = "House2",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description3",
                            Features = 3,
                            LandlordId = 1,
                            NumberOfGuests = 4,
                            PricePerDay = 31f,
                            Rooms = 2,
                            SubTitle = "SubTitle3",
                            Title = "House3",
                            Type = 5
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description4",
                            Features = 4,
                            LandlordId = 1,
                            NumberOfGuests = 4,
                            PricePerDay = 32f,
                            Rooms = 2,
                            SubTitle = "SubTitle4",
                            Title = "House4",
                            Type = 3
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description5",
                            Features = 5,
                            LandlordId = 1,
                            NumberOfGuests = 4,
                            PricePerDay = 33f,
                            Rooms = 2,
                            SubTitle = "SubTitle5",
                            Title = "House5",
                            Type = 4
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description6",
                            Features = 6,
                            LandlordId = 1,
                            NumberOfGuests = 4,
                            PricePerDay = 34f,
                            Rooms = 2,
                            SubTitle = "SubTitle6",
                            Title = "House6",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description7",
                            Features = 7,
                            LandlordId = 1,
                            NumberOfGuests = 4,
                            PricePerDay = 35f,
                            Rooms = 2,
                            SubTitle = "SubTitle7",
                            Title = "House7",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Description8",
                            Features = 8,
                            LandlordId = 1,
                            NumberOfGuests = 4,
                            PricePerDay = 36f,
                            Rooms = 2,
                            SubTitle = "SubTitle8",
                            Title = "House8",
                            Type = 3
                        },
                        new
                        {
                            Id = 9,
                            Description = "Description9",
                            Features = 9,
                            LandlordId = 1,
                            NumberOfGuests = 4,
                            PricePerDay = 37f,
                            Rooms = 2,
                            SubTitle = "SubTitle9",
                            Title = "House9",
                            Type = 4
                        },
                        new
                        {
                            Id = 10,
                            Description = "Description10",
                            Features = 10,
                            LandlordId = 1,
                            NumberOfGuests = 4,
                            PricePerDay = 38f,
                            Rooms = 2,
                            SubTitle = "SubTitle10",
                            Title = "House10",
                            Type = 1
                        });
                });

            modelBuilder.Entity("CsharpWebApiDotNetCore.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LocationId");

                    b.ToTable("Reservation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Discount = 0f,
                            EndDate = new DateTime(2023, 4, 18, 21, 18, 49, 577, DateTimeKind.Local).AddTicks(4884),
                            LocationId = 1,
                            StartDate = new DateTime(2023, 4, 13, 21, 18, 49, 577, DateTimeKind.Local).AddTicks(4849)
                        });
                });

            modelBuilder.Entity("CsharpWebApiDotNetCore.Models.Image", b =>
                {
                    b.HasOne("CsharpWebApiDotNetCore.Models.Location", null)
                        .WithMany("Images")
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("CsharpWebApiDotNetCore.Models.Landlord", b =>
                {
                    b.HasOne("CsharpWebApiDotNetCore.Models.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("CsharpWebApiDotNetCore.Models.Location", b =>
                {
                    b.HasOne("CsharpWebApiDotNetCore.Models.Landlord", "Landlord")
                        .WithMany("Locations")
                        .HasForeignKey("LandlordId");

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("CsharpWebApiDotNetCore.Models.Reservation", b =>
                {
                    b.HasOne("CsharpWebApiDotNetCore.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId");

                    b.HasOne("CsharpWebApiDotNetCore.Models.Location", "Location")
                        .WithMany("Reservations")
                        .HasForeignKey("LocationId");

                    b.Navigation("Customer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CsharpWebApiDotNetCore.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("CsharpWebApiDotNetCore.Models.Landlord", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("CsharpWebApiDotNetCore.Models.Location", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
